# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Fabric Properties
# check these on https://fabricmc.net/develop
mc_version = 1.21.5
loader_version = 0.16.14

# Ahh yes, Parchment, my beloved
librarian_version = 1.+
parchment_version = 2025.04.19

# Mod Properties
mod_version = 1.21.5-1.0.4a
maven_group = com.jerrylu086.netherite_horse_armor
archives_base_name = netherite_horse_armor-fabric

# Dependencies
fabric_version=0.124.0+1.21.5
cloth_config_version = 18.0.145
modmenu_version = 14.0.0-rc.2
