# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Fabric Properties
# check these on https://fabricmc.net/develop
mc_version = 1.21.1
loader_version = 0.17.2
loom_version = 1.11-SNAPSHOT

# Ahh yes, Parchment, my beloved
librarian_version = 1.+
parchment_version = 2024.11.17

# Mod Properties
mod_version = 1.21.1-2.0
maven_group = com.jerrylu086.netherite_horse_armor
archives_base_name = netherite_horse_armor-fabric

# Dependencies
fabric_version = 0.116.6+1.21.1
cloth_config_version = 15.0.140
modmenu_version = 11.0.3