# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.daemon = false
org.gradle.debug = false

# Dependencies
minecraft_version = 1.20.4
minecraft_version_range = [1.20.4,1.21)
neo_version = 20.4.147-beta
neo_version_range = [20.4,)
loader_version_range = [2,)

neogradle.subsystems.parchment.minecraftVersion = 1.20.3
neogradle.subsystems.parchment.mappingsVersion = 2023.12.31

# Mod Properties
mod_id = netherite_horse_armor
mod_name = Netherite Horse Armor
mod_license = MIT License
mod_version = 1.20.4-1.0.4
mod_group_id = com.jerrylu086.netherite_horse_armor
mod_authors = JerryLu086
mod_description = A new horse armor for you to collect!