modLoader="javafml"
loaderVersion="[41,)"
license="MIT License"

[[mods]]
    modId="netherite_horse_armor"
    version="${file.jarVersion}"
    displayName="Netherite Horse Armor"
    logoFile="icon.png"
    authors="jerrylu086"
    description="A new horse armor for you to collect!"
    itemIcon="netherite_horse_armor:netherite_horse_armor"
    configBackground="minecraft:textures/block/netherrack.png"

[[dependencies.netherite_horse_armor]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.netherite_horse_armor]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"