modLoader="javafml"
loaderVersion="[41,)"
license="MIT License"

[[mods]]
    modId="netherite_horse_armor"
    version="1.19.2-1.0.0"
    displayName="Netherite Horse Armor"
    logoFile="pack.png"
    authors="jerrylu086"
    description="A new horse armor for you to collect!"
    itemIcon="netherite_horse_armor:netherite_horse_armor"
    configBackground="minecraft:textures/block/netherrack.png"

[[dependencies.upgradedechests]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.upgradedechests]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"