modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
    modId="netherite_horse_armor"
    version="1.18.2-1.0.4"
    displayName="Netherite Horse Armor"
    logoFile="pack.png"
    authors="jerrylu086"
    description="A new horse armor for you to collect!"
    itemIcon="netherite_horse_armor:netherite_horse_armor"
    configBackground="minecraft:textures/block/netherrack.png"

[[dependencies.netherite_horse_armor]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.netherite_horse_armor]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"