modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
    modId="netherite_horse_armor"
    version="${file.jarVersion}"
    displayName="Netherite Horse Armor"
    logoFile="logo.png"
    authors="JerryLu086"
    description="A new horse armor for you to collect!"
    itemIcon="netherite_horse_armor:netherite_horse_armor"
    configBackground="minecraft:textures/block/netherrack.png"

[[dependencies.netherite_horse_armor]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.netherite_horse_armor]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"